# Site settings
title: 'HyperMonokai: Monokai color theme for HyperTerm'
description: Monokai color theme for HyperTerm
url: https://ixkaito.github.io # the base hostname & protocol for your site
baseurl: '/hypermonokai' # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
exclude:
  - frasco.config.js
  - gulpfile.js
  - LICENSE
  - node_modules
  - npm-debug.log
  - package.json
  - README.md

compress_html:
  # clippings: all
  comments: all
  # endings: all
  ignore:
    envs: [development]
  # blanklines: true
  # profile: true
  # startings: [html, head, body]

twitter:
  id: ixkaito

facebook:
  admin: 1047363919
